services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet4u_web
    ports:
      - "8080:80"          # Apache exposed on http://localhost:8080
      - "5173:5173"        # Vite dev server for HMR
    volumes:
      - .:/var/www/html    # Mount source code into container
    depends_on:
      - db
    command: >
      bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
      && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
      && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: pet4u_db
    restart: always
    environment:
      MYSQL_DATABASE: pet4u_db
      MYSQL_USER: patric
      MYSQL_PASSWORD: patric
      MYSQL_ROOT_PASSWORD: 124358
    ports:
      - "3320:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
